declare module "*.svg";
declare module "*.png";
declare module "*.jpg";
declare module "*.gif";
declare module "*.jpeg";
declare module "*.ico";
declare module "*.otf";
declare module "*.ttf";
declare module "*.mp4";